AWSTemplateFormatVersion: 2010-09-09
Description: >-
  http-feeds-server

Transform:
- AWS::Serverless-2016-10-31

Resources:
  getFeedItemsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/get-feed-items.getFeedItemsHandler
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: Retrieves feed items.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref InventoryFeed
      Environment:
        Variables:
          FEED_TABLE: !Ref InventoryFeed
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: GET
            RequestParameters:
                - method.request.querystring.lastEventId:
                    Required: false
  appendItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/append-item.appendItemHandler
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: Appends an event to the feed.
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref InventoryFeed
      Environment:
        Variables:
          FEED_TABLE: !Ref InventoryFeed
          SHOULD_COMPACT: true
      Events:
        Api:
          Type: Api
          Properties:
            Path: /
            Method: POST

  InventoryFeed:
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - AttributeName: source
          AttributeType: S
        - AttributeName: id
          AttributeType: S
      KeySchema: 
        - AttributeName: source
          KeyType: HASH
        - AttributeName: id
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST

Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
